IA-1794: Update serverless.yml to allow for development deploys to arbitrary stages; fix bug with CONTENT_URL being unused; fix typo in server.js (#1157)
* IA-1794: Update serverless.yml to allow for development deploys to arbitrary stages; fix bug with CONTENT_URL being unused; fix typo in server.js

* IA-1794: Adding dev deploy to circle serverless

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -32,7 +32,8 @@ workflows:
             only:
             - mint
             - qa
-            - /int-\w+/ 
+            - /int-\w+/
+            - /deploy-\w+/
     - cache-dependencies-upper:
         filters:
           branches:
@@ -42,9 +43,9 @@ workflows:
             only:
             - staging
             - production
-        context: snyk   
+        context: snyk
     - test-jest:
-        requires: 
+        requires:
           - cache-dependencies-lower
           - cache-dependencies-upper
         filters:
@@ -103,6 +104,7 @@ workflows:
             - qa
             - /int-\w+/
             - /RELEASE-\d+/
+            - /deploy-\w+/
     - build-package:
         requires: [build-webpack]
         filters:
@@ -119,6 +121,7 @@ workflows:
             - qa
             - /int-\w+/
             - /RELEASE-\d+/
+            - /deploy-\w+/
     - upload-package:
         requires: [build-package]
         filters:
@@ -146,7 +149,7 @@ workflows:
             - /RELEASE-\d+/
         context: sba-gov-lower
     - deploy-package-serverless:
-        requires: [upload-package]
+        requires: [build-package]
         filters:
           branches: 
             only:
@@ -155,6 +158,7 @@ workflows:
             only:
             - mint
             - qa
+            - /deploy-\w+/
         context: sba-gov-lower
     - hold:
         type: approval
@@ -374,7 +378,7 @@ jobs:
       - checkout
       - attach_workspace:
           at: workspace
-      - run:
+      - deploy:
           name: deploy
           shell: /bin/bash -eo pipefail
           command: |
@@ -405,33 +409,30 @@ jobs:
             aws lambda update-function-code --function-name "${LAMBDA_NAME}" --s3-bucket "${BUCKET_NAME}" --s3-key "${ENVIRONMENT}/katana-lambda.zip" --s3-object-version "${VERSION_ID}"
   deploy-package-serverless:
     docker:
-        - image: cimg/node:12.18
+      - image: cimg/node:12.18
     steps:
       - checkout
       - attach_workspace:
           at: workspace
-      - run:
+      - deploy:
           name: deploy
           shell: /bin/bash -eo pipefail
           command: |
-            if [ -z "${CIRCLE_BRANCH}" ]	       
-            then	
-              TARGET_ENVIRONMENT=${CIRCLE_TAG}	
-            else	
-              TARGET_ENVIRONMENT=${CIRCLE_BRANCH}	
-            fi	
-
-            case $TARGET_ENVIRONMENT in	
-              master)	
-                export ENVIRONMENT=mint	
-                ;;
-              *)	
-                export ENVIRONMENT=${CIRCLE_TAG}	
-                ;;	
-            esac
+            if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "main" ]; then
+              # main branch, autodeploy mint
+              TARGET_ENVIRONMENT=mint
+            elif [ ! -z "${CIRCLE_TAG}" ]; then
+              # Tag exists, deploy tag, stripping 'deploy-' prefix if it exists
+              TARGET_ENVIRONMENT=${CIRCLE_TAG}
+              TARGET_ENVIRONMENT=$(echo $TARGET_ENVIRONMENT | sed 's/^deploy-//')
+            else
+              # No tag, not main branch... just leave
+              echo "ERROR: No tag and not on main branch.  Aborting serverless deploy, check workflow settings"
+              exit 1
+            fi
 
             sudo npm i -g serverless
-            serverless deploy --stage ${ENVIRONMENT}
+            serverless deploy --stage ${TARGET_ENVIRONMENT}
   upload-package-serverless-with-approval:
     docker:
       - image: ussba/cc-docker-git-aws:latest
@@ -469,7 +470,7 @@ jobs:
       - checkout
       - attach_workspace:
           at: workspace
-      - run:
+      - deploy:
           name: deploy
           shell: /bin/bash -eo pipefail
           command: |
